name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep database alive
        env:
          DATABASE_URL: ${{ secrets.postgresql+psycopg2://postgres.wzficawmmbqaftsosznm:Konikova1112%40@aws-1-eu-central-1.pooler.supabase.com:5432/postgres }}
        run: |
          psql "$DATABASE_URL" -c "SELECT 1"